apiVersion: v1
kind: Service
metadata:
  name: sniproxy
  namespace: sniproxy
  labels:
    app.kubernetes.io/name: sniproxy
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: sniproxy
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: mqtt-tls
      port: 8883
      targetPort: mqtt-tls
      protocol: TCP
